### ISSUE TITLE
Name Missing!

### ISSUE THREAD

**Issue by JasminLink** [dime-project/meta#8]
Hello, there's sth missing... a name. and sth. too much: w3.org.... for details view screenshots please. 

![dime_screenshot_name w3](https://f.cloud.github.com/assets/5270356/1307073/fd2972a0-31b9-11e3-9e5b-cf76dd0fb730.png)
![dime_screenshot](https://f.cloud.github.com/assets/5270356/1307074/fd30ff02-31b9-11e3-9aca-2cc455456155.png)

**Comment by thielsn** [comment]
"Name missing!" is added by the UI in case the name field in json is empty!

**Comment by ismriv** [comment]
Attribute, profile, and person labels are generated from the contents of the profile's attributes. There was a bug here, where the fullname (empty string) was taken as the label, instead of continue looking up for other non-empty values such as firstname or lastname in this case.

This should be fixed now!

**Comment by thielsn** [comment]
Thanks! :-)
